# Build settings

markdown: kramdown
permalink: pretty
highlighter: pygments
encoding: utf-8

port: 3000

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

sass:
  sass_dir: assets/css
  style: :nested
gems:
  - kramdown 
