works:
- description: Triangles In Motion
  folder: hs-harz
- description: Test2
  folder: proj-1
- description: Test3
  folder: proj-1
- description: Test4
  folder: proj-1
- description: Test5
  folder: proj-1
- description: Test6
  folder: proj-1
- description: Test7
  folder: proj-1
- description: Test8
  folder: proj-1