works:
- description: Triangles In Motion
  folder: hs-harz
  tags: Animation
- description: FatMama World
  folder: fatmama
  tags: Game Dev
- description: HUE
  folder: hue
  tags: Game Dev
- description: Puppy Love
  folder: earthworm
  tags: Game Dev
- description: Grahylus
  folder: grahylus
  tags: Game Dev, VR
- description: Adsquare Teaser
  folder: pm
  tags: Animation, PM